version: "3.9"
services:
  pyapp:
    extends:
      file: ./docker-composes/services-docker-compose.yml
      service:  py.app
    depends_on:
      - esapp
  goapp:
    extends:
      file: ./docker-composes/services-docker-compose.yml
      service:  go.app
    depends_on:
      - esapp
  haproxy:
    extends:
      file: ./docker-composes/services-docker-compose.yml
      service: haproxy
  esapp:
    extends:
      file: ./docker-composes/services-docker-compose.yml
      service: es.app
    depends_on:
      - elasticsearch1
      - elasticsearch2
      - elasticsearch3
  elasticsearch1:
    extends:
      file: ./docker-composes/elastich-docker-compose.yml
      service: elasticsearch1
  elasticsearch2:
    extends:
      file: ./docker-composes/elastich-docker-compose.yml
      service: elasticsearch2
  elasticsearch3:
    extends:
      file: ./docker-composes/elastich-docker-compose.yml
      service: elasticsearch3


volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
